export { default as Text } from './Text';
export { default as CopyRightText } from './CopyRightText';
export { default as Button } from './Button';
export { default as CardProduct } from './CardProduct';
export { default as ProductList } from './ProductList';
export { default as Logo } from './Logo';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as MainContent } from './MainContent';
